spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_USER_NAME}:${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER_NAME}
    password: ${DB_USER_PASSWORD}

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_ID}
            client-secret: ${GOOGLE_SECRET_PASSWORD}

  jpa:
   hibernate:
    ddl-auto: update
   show-sql: true
   properties:
     hibernate.format_sql: true
   database: postgresql
   database-platform: org.hibernate.dialect.PostgreSQLDialect
   open-in-view: false
   generate-ddl: false

  flyway:
    locations: classpath:db/migration
    url: jdbc:postgresql://${DB_USER_NAME}:${DB_HOST}:${DB_PORT}/${DB_NAME}
    user: ${DB_USER_NAME}
    password: ${DB_USER_PASSWORD}
#    schemas: social-network
#    baseline-on-migrate: true
    clean-disabled: false
